version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - REPOSITORY_URI=$ECR_REPOSITORY_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - |
        DOCKERHUB_USER=$(aws secretsmanager get-secret-value --secret-id /trabajoya/dockerhub/username --region $AWS_DEFAULT_REGION --query SecretString --output text 2>/dev/null || echo '')
        DOCKERHUB_PASS=$(aws secretsmanager get-secret-value --secret-id /trabajoya/dockerhub/password --region $AWS_DEFAULT_REGION --query SecretString --output text 2>/dev/null || echo '')
        if [ -n "$DOCKERHUB_USER" ] && [ -n "$DOCKERHUB_PASS" ]; then
          echo "$DOCKERHUB_PASS" | docker login --username "$DOCKERHUB_USER" --password-stdin docker.io || true
        fi
  build:
    commands:
      - echo Building Docker image...
      - docker build -f Dockerfile.prod -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Pushing Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - printf '{"ImageURI":"%s"}' $REPOSITORY_URI:$IMAGE_TAG > imageDetail.json
      - |
        # Forzar actualización de instancias EC2 en Auto Scaling Group
        # Esto hace que las instancias se recreen y descarguen la nueva imagen :latest
        ASG_NAME=${AUTO_SCALING_GROUP_NAME:-""}

        # Si no está configurada, intentar detectar el ASG del stack
        if [ -z "$ASG_NAME" ]; then
          echo "🔍 Variable AUTO_SCALING_GROUP_NAME no configurada. Intentando detectar ASG del stack..."
          STACK_NAME=${STACK_NAME:-"TrabajoYaStack-prod"}
          
          # Buscar ASG en el stack de CloudFormation
          ASG_NAME=$(aws cloudformation describe-stack-resources \
            --stack-name "$STACK_NAME" \
            --query "StackResources[?ResourceType=='AWS::AutoScaling::AutoScalingGroup' && contains(LogicalResourceId, 'Backend')].PhysicalResourceId" \
            --output text 2>/dev/null | head -1 || echo '')
          
          if [ -n "$ASG_NAME" ] && [ "$ASG_NAME" != "None" ]; then
            echo "✅ ASG detectado automáticamente: $ASG_NAME"
          else
            echo "⚠️  No se pudo detectar el ASG automáticamente."
            echo "   Configura la variable AUTO_SCALING_GROUP_NAME en CodeBuild o STACK_NAME si es diferente."
          fi
        fi

        if [ -n "$ASG_NAME" ] && [ "$ASG_NAME" != "None" ]; then
          echo "🔄 Forzando actualización de instancias en Auto Scaling Group: $ASG_NAME"
          
          # Obtener instancias actuales del ASG
          INSTANCES=$(aws autoscaling describe-auto-scaling-groups \
            --auto-scaling-group-names "$ASG_NAME" \
            --query 'AutoScalingGroups[0].Instances[*].InstanceId' \
            --output text 2>/dev/null || echo '')
          
          if [ -n "$INSTANCES" ] && [ "$INSTANCES" != "None" ]; then
            echo "📋 Instancias actuales en el ASG:"
            echo "$INSTANCES" | tr '\t' '\n' | while read INSTANCE_ID; do
              if [ -n "$INSTANCE_ID" ]; then
                echo "   - $INSTANCE_ID"
              fi
            done
            
            # Opción 1: Usar start-instance-refresh (método recomendado, rolling update)
            echo "🔄 Iniciando instance refresh (rolling update)..."
            REFRESH_ID=$(aws autoscaling start-instance-refresh \
              --auto-scaling-group-name "$ASG_NAME" \
              --preferences '{"MinHealthyPercentage": 50, "InstanceWarmup": 300}' \
              --query 'InstanceRefreshId' \
              --output text 2>/dev/null || echo '')
            
            if [ -n "$REFRESH_ID" ] && [ "$REFRESH_ID" != "None" ]; then
              echo "✅ Instance refresh iniciado: $REFRESH_ID"
              echo "   Las instancias se actualizarán gradualmente manteniendo el servicio disponible"
            else
              echo "⚠️  No se pudo iniciar instance refresh. Intentando método alternativo..."
              
              # Opción 2: Terminar instancias una por una (el ASG creará nuevas)
              echo "🔄 Terminando instancias para forzar recreación..."
              echo "$INSTANCES" | tr '\t' '\n' | while read INSTANCE_ID; do
                if [ -n "$INSTANCE_ID" ]; then
                  echo "   Terminando instancia: $INSTANCE_ID"
                  aws autoscaling terminate-instance-in-auto-scaling-group \
                    --instance-id "$INSTANCE_ID" \
                    --no-should-decrement-desired-capacity 2>/dev/null || true
                  # Pequeña pausa entre terminaciones
                  sleep 2
                fi
              done
              echo "✅ Instancias marcadas para terminación. El ASG creará nuevas instancias automáticamente"
            fi
          else
            echo "⚠️  No se encontraron instancias en el ASG. El ASG creará nuevas instancias automáticamente."
          fi
        else
          echo "⚠️  No se pudo determinar el ASG. Saltando actualización de instancias."
          echo "   Para habilitar actualización automática, configura en CodeBuild:"
          echo "   - AUTO_SCALING_GROUP_NAME: nombre del Auto Scaling Group"
          echo "   - STACK_NAME: nombre del stack de CloudFormation (opcional, por defecto: TrabajoYaStack-prod)"
          echo ""
          echo "   Ejemplo: AUTO_SCALING_GROUP_NAME=TrabajoYaStack-prod-BackendASG08C95C34-zb3tOO7qgnCl"
        fi
artifacts:
  files:
    - imageDetail.json
