post_build:
  commands:
    - echo "Push de imagen a ECR"
    - docker push $REPOSITORY_URI:$IMAGE_TAG
    - docker push $REPOSITORY_URI:latest
    - echo "✅ Migraciones se ejecutarán automáticamente al iniciar el contenedor"
    - echo "💡 Esto no tiene costo adicional - las migraciones corren en el mismo contenedor"
    - echo "🔄 Actualizando instancias EC2 existentes (sin crear nuevas)..."
    - |
      source /tmp/build.env 2>/dev/null || SKIP_DEPLOY="false"
      
      if [ "$SKIP_DEPLOY" = "true" ]; then
        echo "⏭️  Saltando deployment - imagen no ha cambiado"
        exit 0
      fi
      
      TARGET_IMAGE="$REPOSITORY_URI:$IMAGE_TAG"
      PROJECT_NAME="${PROJECT_NAME:-trabajoya-prod}"
      CONTAINER_NAME="${PROJECT_NAME}-backend"
      
      echo "Imagen objetivo: $TARGET_IMAGE"
      echo "Nombre del contenedor: $CONTAINER_NAME"
      echo "Buscando instancias EC2..."
      
      # Permitir especificar instancia directamente
      if [ -n "$EC2_INSTANCE_ID" ]; then
        echo "✅ Usando instancia especificada: $EC2_INSTANCE_ID"
        INSTANCE_IDS="$EC2_INSTANCE_ID"
      else
        # Buscar por ASG
        echo "🔍 Buscando Auto Scaling Groups..."
        ASG_NAMES=""
        ASG_NAMES=$(aws autoscaling describe-auto-scaling-groups --query "AutoScalingGroups[?contains(AutoScalingGroupName, 'trabajoya') || contains(AutoScalingGroupName, 'prod')].AutoScalingGroupName" --output text 2>/dev/null || echo "")
        
        INSTANCE_IDS=""
        
        if [ -n "$ASG_NAMES" ]; then
          echo "✅ Auto Scaling Groups encontrados: $ASG_NAMES"
          for ASG_NAME in $ASG_NAMES; do
            echo "   Procesando ASG: $ASG_NAME"
            ASG_INSTANCES=$(aws autoscaling describe-auto-scaling-groups --auto-scaling-group-names "$ASG_NAME" --query "AutoScalingGroups[0].Instances[?HealthStatus=='Healthy' && LifecycleState=='InService'].InstanceId" --output text 2>/dev/null || echo "")
            if [ -n "$ASG_INSTANCES" ]; then
              INSTANCE_IDS="$INSTANCE_IDS $ASG_INSTANCES"
            fi
          done
          INSTANCE_IDS=$(echo $INSTANCE_IDS | tr ' ' '\n' | sort -u | tr '\n' ' ' | xargs)
        fi
        
        # Si no encuentra por ASG, buscar directamente
        if [ -z "$INSTANCE_IDS" ]; then
          echo "⚠️  No se encontraron instancias por ASG. Buscando directamente..."
          INSTANCE_IDS=$(aws ec2 describe-instances --filters "Name=instance-state-name,Values=running" "Name=tag:Name,Values=*trabajoya*" --query "Reservations[*].Instances[*].InstanceId" --output text 2>/dev/null || echo "")
          
          if [ -z "$INSTANCE_IDS" ]; then
            echo "⚠️  Buscando todas las instancias corriendo..."
            ALL_INSTANCES=$(aws ec2 describe-instances --filters "Name=instance-state-name,Values=running" --query "Reservations[*].Instances[*].[InstanceId,Tags[?Key=='Name'].Value|[0],PrivateIpAddress]" --output text 2>/dev/null || echo "")
            
            echo "📋 Instancias corriendo encontradas:"
            echo "$ALL_INSTANCES"
            
            # Buscar por CloudFormation stack
            STACK_NAME=$(aws cloudformation list-stacks --stack-status-filter CREATE_COMPLETE UPDATE_COMPLETE --query "StackSummaries[?contains(StackName, 'trabajoya') && contains(StackName, 'prod')].StackName" --output text 2>/dev/null | head -n 1 || echo "")
            
            if [ -n "$STACK_NAME" ]; then
              echo "🔍 Stack encontrado: $STACK_NAME"
              STACK_INSTANCES=$(aws ec2 describe-instances --filters "Name=instance-state-name,Values=running" "Name=tag:aws:cloudformation:stack-name,Values=$STACK_NAME" --query "Reservations[*].Instances[*].InstanceId" --output text 2>/dev/null || echo "")
              
              if [ -n "$STACK_INSTANCES" ]; then
                echo "✅ Instancias encontradas en stack: $STACK_INSTANCES"
                INSTANCE_IDS="$STACK_INSTANCES"
              fi
            fi
          fi
        fi
      fi
      
      if [ -z "$INSTANCE_IDS" ]; then
        echo "⚠️  No se encontraron instancias activas"
        exit 0
      fi
      
      echo "📋 Instancias encontradas: $INSTANCE_IDS"
      
      # Preparar comandos para SSM
      cat > /tmp/update-commands.json << 'EOFCMDS'
      [
        "set -e",
        "REGION=$(curl -s http://169.254.169.254/latest/meta-data/placement/region)",
        "ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)",
        "aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com",
        "docker pull TARGET_IMAGE_PLACEHOLDER || docker pull REPOSITORY_PLACEHOLDER:latest",
        "if docker ps --format '{{.Names}}' | grep -q '^CONTAINER_NAME_PLACEHOLDER$'; then docker restart CONTAINER_NAME_PLACEHOLDER && echo '✅ Contenedor reiniciado' || (docker stop CONTAINER_NAME_PLACEHOLDER && docker rm CONTAINER_NAME_PLACEHOLDER && echo '⚠️  Contenedor detenido'); else echo '⚠️  Contenedor no corriendo'; fi",
        "echo '✅ Actualización completada'"
      ]
      EOFCMDS
      
      # Reemplazar placeholders
      sed -i "s|TARGET_IMAGE_PLACEHOLDER|${TARGET_IMAGE}|g" /tmp/update-commands.json
      sed -i "s|REPOSITORY_PLACEHOLDER|${REPOSITORY_URI}|g" /tmp/update-commands.json
      sed -i "s|CONTAINER_NAME_PLACEHOLDER|${CONTAINER_NAME}|g" /tmp/update-commands.json
      
      COMMANDS_JSON=$(cat /tmp/update-commands.json)
      
      # Actualizar cada instancia
      for INSTANCE_ID in $INSTANCE_IDS; do
        echo "🚀 Actualizando instancia: $INSTANCE_ID"
        
        COMMAND_ID=$(aws ssm send-command --instance-ids "$INSTANCE_ID" --document-name "AWS-RunShellScript" --parameters "commands=${COMMANDS_JSON}" --timeout-seconds 600 --query 'Command.CommandId' --output text 2>/dev/null || echo "")
        
        if [ -n "$COMMAND_ID" ] && [ "$COMMAND_ID" != "None" ]; then
          echo "✅ Comando enviado (ID: $COMMAND_ID)"
          
          echo "⏳ Esperando actualización..."
          for i in $(seq 1 30); do
            STATUS=$(aws ssm get-command-invocation --command-id "$COMMAND_ID" --instance-id "$INSTANCE_ID" --query 'Status' --output text 2>/dev/null || echo "Pending")
            
            if [ "$STATUS" = "Success" ]; then
              echo "✅ Instancia $INSTANCE_ID actualizada exitosamente"
              break
            elif [ "$STATUS" = "Failed" ] || [ "$STATUS" = "Cancelled" ] || [ "$STATUS" = "TimedOut" ]; then
              echo "⚠️  Instancia $INSTANCE_ID falló: $STATUS"
              break
            fi
            
            if [ $i -lt 30 ]; then
              sleep 10
            fi
          done
        else
          echo "⚠️  No se pudo enviar comando a $INSTANCE_ID"
        fi
      done
      
      echo "💡 Las migraciones se ejecutarán al iniciar el contenedor"