version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - REPOSITORY_URI=$ECR_REPOSITORY_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - |
        DOCKERHUB_USER=$(aws secretsmanager get-secret-value --secret-id /trabajoya/dockerhub/username --region $AWS_DEFAULT_REGION --query SecretString --output text 2>/dev/null || echo '')
        DOCKERHUB_PASS=$(aws secretsmanager get-secret-value --secret-id /trabajoya/dockerhub/password --region $AWS_DEFAULT_REGION --query SecretString --output text 2>/dev/null || echo '')
        if [ -n "$DOCKERHUB_USER" ] && [ -n "$DOCKERHUB_PASS" ]; then
          echo "$DOCKERHUB_PASS" | docker login --username "$DOCKERHUB_USER" --password-stdin docker.io || true
        fi
  build:
    commands:
      - echo Building Docker image...
      - docker build -f Dockerfile.prod -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo "=========================================="
      - echo "INICIANDO POST_BUILD - Actualizacion ASG"
      - echo "=========================================="
      - echo Pushing Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - printf '{"ImageURI":"%s"}' $REPOSITORY_URI:$IMAGE_TAG > imageDetail.json
      - echo "Imagenes subidas a ECR. Iniciando actualizacion de instancias..."
      - |
        # Forzar actualización de instancias EC2 en Auto Scaling Group
        # Esto hace que las instancias se recreen y descarguen la nueva imagen :latest
        ASG_NAME=${AUTO_SCALING_GROUP_NAME:-""}

        # Si no está configurada, intentar detectar el ASG del stack
        if [ -z "$ASG_NAME" ]; then
          echo "Variable AUTO_SCALING_GROUP_NAME no configurada. Intentando detectar ASG del stack..."
          STACK_NAME=${STACK_NAME:-"TrabajoYaStack-prod"}
          
          # Buscar ASG en el stack de CloudFormation
          ASG_NAME=$(aws cloudformation describe-stack-resources \
            --stack-name "$STACK_NAME" \
            --query "StackResources[?ResourceType=='AWS::AutoScaling::AutoScalingGroup' && contains(LogicalResourceId, 'Backend')].PhysicalResourceId" \
            --output text 2>/dev/null | head -1 || echo '')
          
          if [ -n "$ASG_NAME" ] && [ "$ASG_NAME" != "None" ]; then
            echo "ASG detectado automaticamente: $ASG_NAME"
          else
            echo "No se pudo detectar el ASG automaticamente. Configura AUTO_SCALING_GROUP_NAME en CodeBuild."
          fi
        else
          echo "Usando ASG de variable de entorno: $ASG_NAME"
        fi

        if [ -n "$ASG_NAME" ] && [ "$ASG_NAME" != "None" ]; then
          echo "Forzando actualizacion de instancias en Auto Scaling Group: $ASG_NAME"
          
          # Obtener informacion completa del ASG
          ASG_INFO=$(aws autoscaling describe-auto-scaling-groups \
            --auto-scaling-group-names "$ASG_NAME" \
            --output json 2>/dev/null || echo '{}')
          
          if [ -n "$ASG_INFO" ] && [ "$ASG_INFO" != '{}' ]; then
            # Extraer informacion del ASG usando jq
            DESIRED=$(echo "$ASG_INFO" | jq -r '.AutoScalingGroups[0].DesiredCapacity // 0')
            MIN=$(echo "$ASG_INFO" | jq -r '.AutoScalingGroups[0].MinSize // 0')
            MAX=$(echo "$ASG_INFO" | jq -r '.AutoScalingGroups[0].MaxSize // 0')
            echo "Estado del ASG: Desired=$DESIRED, Min=$MIN, Max=$MAX"
            
            # Obtener instancias
            INSTANCES=$(echo "$ASG_INFO" | jq -r '.AutoScalingGroups[0].Instances[]?.InstanceId // empty' | tr '\n' ' ' || echo '')
            
            if [ -n "$INSTANCES" ] && [ "$INSTANCES" != ' ' ]; then
              echo "Instancias actuales en el ASG:"
              echo "$INSTANCES" | tr ' ' '\n' | while read INSTANCE_ID; do
                if [ -n "$INSTANCE_ID" ]; then
                  STATE=$(echo "$ASG_INFO" | jq -r ".AutoScalingGroups[0].Instances[] | select(.InstanceId == \"$INSTANCE_ID\") | .LifecycleState // \"unknown\"")
                  echo "   - $INSTANCE_ID (Estado: $STATE)"
                fi
              done
              
              # Opcion 1: Usar start-instance-refresh (metodo recomendado, rolling update)
              echo "Iniciando instance refresh (rolling update)..."
              REFRESH_ID=$(aws autoscaling start-instance-refresh \
                --auto-scaling-group-name "$ASG_NAME" \
                --preferences '{"MinHealthyPercentage": 50, "InstanceWarmup": 300}' \
                --query 'InstanceRefreshId' \
                --output text 2>/dev/null || echo '')
              
              if [ -n "$REFRESH_ID" ] && [ "$REFRESH_ID" != "None" ]; then
                echo "Instance refresh iniciado: $REFRESH_ID"
                echo "   Las instancias se actualizaran gradualmente manteniendo el servicio disponible"
              else
                echo "No se pudo iniciar instance refresh. Verificando si ya hay uno en progreso..."
                
                # Verificar si ya hay un instance refresh activo
                ACTIVE_REFRESH=$(aws autoscaling describe-instance-refreshes \
                  --auto-scaling-group-name "$ASG_NAME" \
                  --query 'InstanceRefreshes[?Status==`InProgress` || Status==`Pending`].InstanceRefreshId' \
                  --output text 2>/dev/null || echo '')
                
                if [ -n "$ACTIVE_REFRESH" ]; then
                  echo "Ya hay un instance refresh en progreso: $ACTIVE_REFRESH"
                else
                  echo "Intentando metodo alternativo: forzar nuevo despliegue..."
                  if [ "$DESIRED" -gt 0 ]; then
                    echo "   El ASG tiene DesiredCapacity=$DESIRED, las instancias se crearan automaticamente"
                  else
                    echo "DesiredCapacity es 0. El ASG no creara nuevas instancias automaticamente."
                  fi
                fi
              fi
            else
              echo "No se encontraron instancias en el ASG (DesiredCapacity=$DESIRED)."
              if [ "$DESIRED" -eq 0 ]; then
                echo "DesiredCapacity es 0. El ASG creara instancias cuando sea necesario."
              else
                echo "El ASG deberia crear nuevas instancias automaticamente con la nueva imagen."
              fi
            fi
          else
            echo "No se pudo obtener informacion del ASG."
          fi
        else
          echo "No se pudo determinar el ASG. Saltando actualizacion de instancias."
          echo "   Para habilitar actualizacion automatica, configura en CodeBuild:"
          echo "   - AUTO_SCALING_GROUP_NAME: nombre del Auto Scaling Group"
          echo "   - STACK_NAME: nombre del stack de CloudFormation (opcional, por defecto: TrabajoYaStack-prod)"
          echo ""
          echo "   Ejemplo: AUTO_SCALING_GROUP_NAME=TrabajoYaStack-prod-BackendASG08C95C34-zb3tOO7qgnCl"
        fi
artifacts:
  files:
    - imageDetail.json
