version: 0.2

phases:
  pre_build:
    commands:
      - echo "Login a Amazon ECR"
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI
      - export REPOSITORY_URI=$ECR_REPOSITORY_URI
      - export COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - export IMAGE_TAG=${COMMIT_HASH:-latest}
      - echo "Repositorio:$REPOSITORY_URI"
      - echo "Tag:$IMAGE_TAG"

  build:
    commands:
      - echo "Build iniciado el $(date)"
      - docker pull public.ecr.aws/docker/library/node:20-alpine || echo "Warning"
      - docker build --no-cache --pull -f Dockerfile.prod -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest

  post_build:
    commands:
      - echo "Push de imagen a ECR"
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
      - echo "Actualizando instancias EC2..."
      - |
        TARGET_IMAGE="$REPOSITORY_URI:$IMAGE_TAG"
        DEPLOY_REGION="${AWS_DEFAULT_REGION:-us-east-1}"
        CONTAINER_NAME="trabajoya-prod-backend"

        echo "Imagen: $TARGET_IMAGE"
        echo "Region: $DEPLOY_REGION"

        if [ -n "$EC2_INSTANCE_ID" ]; then
          INSTANCE_IDS="$EC2_INSTANCE_ID"
        else
          ASG_NAMES=$(aws autoscaling describe-auto-scaling-groups --query "AutoScalingGroups[?contains(AutoScalingGroupName,'trabajoya')||contains(AutoScalingGroupName,'prod')].AutoScalingGroupName" --output text 2>/dev/null || echo "")
          INSTANCE_IDS=""
          if [ -n "$ASG_NAMES" ]; then
            for ASG_NAME in $ASG_NAMES; do
              ASG_INSTANCES=$(aws autoscaling describe-auto-scaling-groups --auto-scaling-group-names "$ASG_NAME" --query "AutoScalingGroups[0].Instances[?HealthStatus=='Healthy'&&LifecycleState=='InService'].InstanceId" --output text 2>/dev/null || echo "")
              if [ -n "$ASG_INSTANCES" ]; then
                INSTANCE_IDS="$INSTANCE_IDS $ASG_INSTANCES"
              fi
            done
          fi
        fi

        if [ -z "$INSTANCE_IDS" ]; then
          echo "No hay instancias"
          exit 0
        fi

        echo "Instancias: $INSTANCE_IDS"

        for INSTANCE_ID in $INSTANCE_IDS; do
          echo ""
          echo "=== Actualizando $INSTANCE_ID ==="
          
          SCRIPT="set -e; REGION=${DEPLOY_REGION}; ACCOUNT=\$(aws sts get-caller-identity --query Account --output text); aws ecr get-login-password --region \$REGION | docker login --username AWS --password-stdin \$ACCOUNT.dkr.ecr.\$REGION.amazonaws.com; docker pull ${TARGET_IMAGE} || docker pull ${REPOSITORY_URI}:latest; if docker ps --format '{{.Names}}' | grep -q '^${CONTAINER_NAME}\$'; then docker restart ${CONTAINER_NAME} && echo 'OK' || (docker stop ${CONTAINER_NAME}; docker rm ${CONTAINER_NAME}); else echo 'No corriendo'; fi"
          
          COMMAND_ID=$(aws ssm send-command \
            --instance-ids "$INSTANCE_ID" \
            --document-name "AWS-RunShellScript" \
            --parameters commands="$SCRIPT" \
            --timeout-seconds 600 \
            --query 'Command.CommandId' \
            --output text 2>&1)
          
          if [ -z "$COMMAND_ID" ] || echo "$COMMAND_ID" | grep -q "Error"; then
            echo "ERROR SSM: $COMMAND_ID"
            continue
          fi
          
          echo "Comando: $COMMAND_ID"
          
          for i in $(seq 1 60); do
            STATUS=$(aws ssm get-command-invocation --command-id "$COMMAND_ID" --instance-id "$INSTANCE_ID" --query 'Status' --output text 2>/dev/null || echo "Pending")
            
            if [ "$STATUS" = "Success" ]; then
              echo "✅ OK"
              aws ssm get-command-invocation --command-id "$COMMAND_ID" --instance-id "$INSTANCE_ID" --query 'StandardOutputContent' --output text 2>/dev/null
              break
            elif [ "$STATUS" = "Failed" ]; then
              echo "❌ FALLO"
              aws ssm get-command-invocation --command-id "$COMMAND_ID" --instance-id "$INSTANCE_ID" --query 'StandardErrorContent' --output text 2>/dev/null
              aws ssm get-command-invocation --command-id "$COMMAND_ID" --instance-id "$INSTANCE_ID" --query 'StandardOutputContent' --output text 2>/dev/null
              break
            elif [ "$STATUS" != "InProgress" ] && [ "$STATUS" != "Pending" ]; then
              echo "Estado: $STATUS"
              break
            fi
            
            [ $((i % 6)) -eq 0 ] && echo "Esperando... ($i/60)"
            sleep 10
          done
        done

        echo "Deployment completado"

artifacts:
  files:
    - "**/*"
