version: 0.2

env:
  variables:
    PROJECT_NAME: "trabajoya-prod"
    CONTAINER_PORT: "4000"
    APP_CONFIG_SECRET_ID: "/trabajoya-prod/app/config"
    DB_CREDENTIALS_SECRET_ID: "/trabajoya-prod/database/credentials"

phases:
  pre_build:
    commands:
      - echo "Login a Amazon ECR"
      - aws --version
      - aws ecr get-login-password --region "$AWS_DEFAULT_REGION" | docker login --username AWS --password-stdin "$ECR_REPOSITORY_URI"
      - REPOSITORY_URI="$ECR_REPOSITORY_URI"
      - COMMIT_HASH="$(echo "$CODEBUILD_RESOLVED_SOURCE_VERSION" | cut -c 1-7)"
      - IMAGE_TAG="${COMMIT_HASH:-latest}"
      - echo "Repositorio=$REPOSITORY_URI"
      - echo "Tag=$IMAGE_TAG"

  build:
    commands:
      - echo "Build iniciado el $(date)"
      - echo "Commit=$CODEBUILD_RESOLVED_SOURCE_VERSION"
      - echo "Rama=$CODEBUILD_SOURCE_VERSION"
      - echo "Verificando código fuente antes del build..."
      - ls -la src/config/aws-config.service.ts || echo "⚠️  Archivo no encontrado"
      - echo "Verificando contenido del archivo..."
      - head -n 5 src/config/aws-config.service.ts
      - echo "Buscando texto actualizado en el archivo..."
      - grep -q "\[SSM\] Cargando parámetros con prefijo" src/config/aws-config.service.ts && echo "✅ Código actualizado detectado" || echo "⚠️  Código antiguo detectado"
      - echo "Mostrando líneas relevantes del archivo..."
      - grep -n "Cargando parámetros" src/config/aws-config.service.ts || echo "No se encontró el texto"
      - echo "Construyendo imagen Docker con --no-cache (sin caché)..."
      - docker build --no-cache --pull --build-arg BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')" --build-arg GIT_COMMIT="$CODEBUILD_RESOLVED_SOURCE_VERSION" -f Dockerfile.prod -t "$REPOSITORY_URI:$IMAGE_TAG" .
      - docker tag "$REPOSITORY_URI:$IMAGE_TAG" "$REPOSITORY_URI:latest"
      - echo "Subiendo imagenes a ECR..."
      - docker push "$REPOSITORY_URI:$IMAGE_TAG"
      - docker push "$REPOSITORY_URI:latest"
      - echo "Build completado y subido=$REPOSITORY_URI:$IMAGE_TAG"
      - echo "⏳ Esperando 15 segundos para que ECR indexe las imágenes..."
      - sleep 15

  post_build:
    commands:
      - echo "Post build iniciado"
      - chmod +x ./scripts/deploy-via-ssm.sh
      - ./scripts/deploy-via-ssm.sh

artifacts:
  files:
    - "**/*"
