steps:
  # Construir la imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.gcp'
      - '-t'
      - 'gcr.io/$PROJECT_ID/trabajoya-backend:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/trabajoya-backend:latest'
      - '.'

  # Enviar la imagen al Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/trabajoya-backend'

  # Paso 1: Configurar y ejecutar secrets primero (migraciones)
  # Crear/actualizar Cloud Run Job para migraciones
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "📦 Configurando Cloud Run Job para migraciones..."
        
        # Crear o actualizar el job de migraciones
        
        # Intentar crear el job primero
        if ! gcloud run jobs describe trabajoya-migrate --region=us-central1 >/dev/null 2>&1; then
          echo "📦 Creando nuevo job trabajoya-migrate..."
          gcloud run jobs create trabajoya-migrate \
            --image=gcr.io/$PROJECT_ID/trabajoya-backend:$SHORT_SHA \
            --region=us-central1 \
            --command="node" \
            --args="scripts/run-migrations.js" \
            --set-secrets="TRABAJOYA_SECRETS=trabajoya-secrets:latest" \
            --set-env-vars="NODE_ENV=production" \
            --add-cloudsql-instances=${_CLOUD_SQL_INSTANCE} \
            --memory=1Gi \
            --cpu=1 \
            --max-retries=1 \
            --task-timeout=600
        else
          echo "🔄 Actualizando job trabajoya-migrate existente..."
          # Actualizar el job con todos los parámetros, incluyendo Cloud SQL
          # Asegurar que la conexión Cloud SQL esté configurada usando --add-cloudsql-instances
          # en la misma actualización para que se aplique correctamente
          gcloud run jobs update trabajoya-migrate \
            --image=gcr.io/$PROJECT_ID/trabajoya-backend:$SHORT_SHA \
            --region=us-central1 \
            --command="node" \
            --args="scripts/run-migrations.js" \
            --set-secrets="TRABAJOYA_SECRETS=trabajoya-secrets:latest" \
            --set-env-vars="NODE_ENV=production" \
            --add-cloudsql-instances=${_CLOUD_SQL_INSTANCE} \
            --memory=1Gi \
            --cpu=1 \
            --max-retries=1 \
            --task-timeout=600
          
          # Verificar que Cloud SQL esté configurado (solo verificación, no bloquea)
          echo "✅ Verificando configuración de Cloud SQL..."
          CURR_SQL_INST=$$(gcloud run jobs describe trabajoya-migrate --region=us-central1 --format="value(spec.template.spec.cloudSqlInstances)" 2>/dev/null || echo "")
          if [ -z "$$CURR_SQL_INST" ] || [ "$$CURR_SQL_INST" != "${_CLOUD_SQL_INSTANCE}" ]; then
            echo "⚠️  Cloud SQL no está configurado correctamente, forzando actualización..."
            gcloud run jobs update trabajoya-migrate \
              --region=us-central1 \
              --add-cloudsql-instances=${_CLOUD_SQL_INSTANCE}
          else
            echo "✅ Cloud SQL ya está configurado correctamente"
          fi
        fi
        
        echo "🚀 Ejecutando migraciones..."
        gcloud run jobs execute trabajoya-migrate \
          --region=us-central1 \
          --wait || echo "⚠️  Error en migraciones, pero continuando..."

  # Paso 2: Ejecutar seed después de migraciones
  # Crear/actualizar Cloud Run Job para seed
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🌱 Configurando Cloud Run Job para seed..."
        
        # Crear o actualizar el job de seed
        
        # Intentar crear el job primero
        if ! gcloud run jobs describe trabajoya-seed --region=us-central1 >/dev/null 2>&1; then
          echo "📦 Creando nuevo job trabajoya-seed..."
          gcloud run jobs create trabajoya-seed \
            --image=gcr.io/$PROJECT_ID/trabajoya-backend:$SHORT_SHA \
            --region=us-central1 \
            --command="node" \
            --args="scripts/run-seed.js" \
            --set-secrets="TRABAJOYA_SECRETS=trabajoya-secrets:latest" \
            --set-env-vars="NODE_ENV=production" \
            --add-cloudsql-instances=${_CLOUD_SQL_INSTANCE} \
            --memory=1Gi \
            --cpu=1 \
            --max-retries=1 \
            --task-timeout=600
        else
          echo "🔄 Actualizando job trabajoya-seed existente..."
          # Primero limpiar conexiones Cloud SQL existentes para asegurar configuración limpia
          echo "🧹 Limpiando conexiones Cloud SQL existentes..."
          gcloud run jobs update trabajoya-seed \
            --region=us-central1 \
            --clear-cloudsql-instances || echo "⚠️  No había conexiones previas o no se pudieron limpiar"
          
          # Actualizar el job con todos los parámetros, incluyendo Cloud SQL
          # Asegurar que la conexión Cloud SQL esté configurada usando --add-cloudsql-instances
          # en la misma actualización para que se aplique correctamente
          gcloud run jobs update trabajoya-seed \
            --image=gcr.io/$PROJECT_ID/trabajoya-backend:$SHORT_SHA \
            --region=us-central1 \
            --command="node" \
            --args="scripts/run-seed.js" \
            --set-secrets="TRABAJOYA_SECRETS=trabajoya-secrets:latest" \
            --set-env-vars="NODE_ENV=production" \
            --add-cloudsql-instances=${_CLOUD_SQL_INSTANCE} \
            --memory=1Gi \
            --cpu=1 \
            --max-retries=1 \
            --task-timeout=600
          
          # Verificar que Cloud SQL esté configurado (solo verificación, no bloquea)
          echo "✅ Verificando configuración de Cloud SQL..."
          CURR_SQL_INST=$$(gcloud run jobs describe trabajoya-seed --region=us-central1 --format="value(spec.template.spec.cloudSqlInstances)" 2>/dev/null || echo "")
          if [ -z "$$CURR_SQL_INST" ] || [ "$$CURR_SQL_INST" != "${_CLOUD_SQL_INSTANCE}" ]; then
            echo "⚠️  Cloud SQL no está configurado correctamente, forzando actualización..."
            gcloud run jobs update trabajoya-seed \
              --region=us-central1 \
              --add-cloudsql-instances=${_CLOUD_SQL_INSTANCE}
          else
            echo "✅ Cloud SQL ya está configurado correctamente"
          fi
        fi
        
        echo "🚀 Ejecutando seed (solo si la DB está vacía)..."
        gcloud run jobs execute trabajoya-seed \
          --region=us-central1 \
          --wait || echo "⚠️  Error en seed, pero continuando..."

  # Paso 3: Desplegar servicio principal DESPUÉS de que los secrets estén configurados y la DB esté lista
  # Desplegar a Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🧹 Limpiando secrets y conexiones Cloud SQL antiguas (si existen)..."
        gcloud run services update trabajoya-backend \
          --region=${_REGION} \
          --clear-secrets \
          --clear-cloudsql-instances \
          --no-traffic || echo "⚠️  No se pudieron limpiar (puede ser normal si el servicio no existe)"
        
        echo "🚀 Desplegando servicio (secrets y DB ya configurados)..."
        # --set-secrets monta el secret como variable de entorno TRABAJOYA_SECRETS
        # El script start-gcp.sh carga estos secrets antes de iniciar Node.js
        gcloud run deploy trabajoya-backend \
          --image=gcr.io/$PROJECT_ID/trabajoya-backend:$SHORT_SHA \
          --region=${_REGION} \
          --platform=managed \
          --allow-unauthenticated \
          --memory=${_MEMORY} \
          --cpu=${_CPU} \
          --min-instances=${_MIN_INSTANCES} \
          --max-instances=${_MAX_INSTANCES} \
          --port=8080 \
          --timeout=300 \
          --concurrency=${_CONCURRENCY} \
          --set-env-vars="NODE_ENV=production" \
          --set-secrets="TRABAJOYA_SECRETS=trabajoya-secrets:latest" \
          --add-cloudsql-instances=${_CLOUD_SQL_INSTANCE}
        
        # Verificar que Cloud SQL esté configurado correctamente
        echo "✅ Verificando configuración de Cloud SQL..."
        CURR_SQL_INST=$$(gcloud run services describe trabajoya-backend --region=${_REGION} --format="value(spec.template.spec.containers[0].cloudSqlInstances)" 2>/dev/null || echo "")
        if [ -z "$$CURR_SQL_INST" ] || [ "$$CURR_SQL_INST" != "${_CLOUD_SQL_INSTANCE}" ]; then
          echo "⚠️  Cloud SQL no está configurado correctamente, forzando actualización..."
          gcloud run services update trabajoya-backend \
            --region=${_REGION} \
            --add-cloudsql-instances=${_CLOUD_SQL_INSTANCE}
        else
          echo "✅ Cloud SQL ya está configurado correctamente"
        fi

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

substitutions:
  _REGION: 'us-central1'
  _MEMORY: '2Gi'
  _CPU: '2'
  _MIN_INSTANCES: '1'
  _MAX_INSTANCES: '10'
  _CONCURRENCY: '80'
  _CLOUD_SQL_INSTANCE: "$PROJECT_ID:us-central1:trabajoya-db"


timeout: '1200s'

