steps:
  # Construir la imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.gcp'
      - '-t'
      - 'gcr.io/$PROJECT_ID/trabajoya-backend:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/trabajoya-backend:latest'
      - '.'

  # Enviar la imagen al Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/trabajoya-backend'

  # Desplegar a Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'trabajoya-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/trabajoya-backend:$SHORT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '${_MEMORY}'
      - '--cpu'
      - '${_CPU}'
      - '--min-instances'
      - '${_MIN_INSTANCES}'
      - '--max-instances'
      - '${_MAX_INSTANCES}'
      - '--port'
      - '8080'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '${_CONCURRENCY}'
      - '--set-env-vars'
      - 'NODE_ENV=production,PORT=8080'
      - '--update-secrets'
      - 'DATABASE_URL=DATABASE_URL:latest,JWT_ACCESS_SECRET=JWT_ACCESS_SECRET:latest,JWT_REFRESH_SECRET=JWT_REFRESH_SECRET:latest,GOOGLE_CLIENT_ID=GOOGLE_CLIENT_ID:latest,GOOGLE_CLIENT_SECRET=GOOGLE_CLIENT_SECRET:latest,OPENAI_API_KEY=OPENAI_API_KEY:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

substitutions:
  _REGION: 'us-central1'
  _MEMORY: '2Gi'
  _CPU: '2'
  _MIN_INSTANCES: '1'
  _MAX_INSTANCES: '10'
  _CONCURRENCY: '80'

timeout: '1200s'

