steps:
  # Construir la imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.gcp'
      - '-t'
      - 'gcr.io/$PROJECT_ID/trabajoya-backend:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/trabajoya-backend:latest'
      - '.'

  # Enviar la imagen al Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/trabajoya-backend'

  # Paso 1: Configurar y ejecutar migraciones
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "📦 Configurando y ejecutando migraciones..."
        
        # Verificar que el secreto DATABASE_URL existe
        echo "🔍 Verificando que el secreto DATABASE_URL existe..."
        if ! gcloud secrets describe DATABASE_URL --project=trabajo-ya-483316 >/dev/null 2>&1; then
          echo "❌ Error: El secreto DATABASE_URL no existe en Secret Manager"
          exit 1
        fi
        echo "✅ Secreto DATABASE_URL verificado"
        
        # Verificar si el job existe y su estado
        JOB_EXISTS=$$(gcloud run jobs describe trabajoya-migrate --region=us-central1 --format="value(name)" 2>/dev/null || echo "")
        NEEDS_CREATE=false
        
        if [ -n "$${JOB_EXISTS}" ]; then
          echo "ℹ️  El job trabajoya-migrate ya existe, verificando estado..."
          
          # Verificar si está en estado de error
          JOB_READY=$$(gcloud run jobs describe trabajoya-migrate --region=us-central1 --format="value(status.conditions[0].status)" 2>/dev/null || echo "False")
          
          if [ "$${JOB_READY}" != "True" ]; then
            echo "⚠️  El job está en estado de error o no listo, eliminándolo para recrear..."
            gcloud run jobs delete trabajoya-migrate --region=us-central1 --quiet 2>/dev/null || true
            sleep 2
            NEEDS_CREATE=true
          else
            echo "✅ El job existe y está listo, actualizando..."
            if ! gcloud run jobs update trabajoya-migrate \
              --region=us-central1 \
              --image=gcr.io/$PROJECT_ID/trabajoya-backend:$SHORT_SHA \
              --update-secrets=DATABASE_URL=DATABASE_URL:latest \
              --set-env-vars="NODE_ENV=production" \
              --set-cloudsql-instances=${_CLOUD_SQL_INSTANCE} \
              --memory=1Gi \
              --cpu=1 \
              --max-retries=1 \
              --task-timeout=300 2>/dev/null; then
              echo "⚠️  Error al actualizar, eliminando y recreando..."
              gcloud run jobs delete trabajoya-migrate --region=us-central1 --quiet 2>/dev/null || true
              sleep 2
              NEEDS_CREATE=true
            else
              echo "✅ Job actualizado correctamente"
            fi
          fi
        else
          NEEDS_CREATE=true
        fi
        
        # Crear el job si es necesario
        if [ "$${NEEDS_CREATE}" = "true" ]; then
          echo "📝 Creando job trabajoya-migrate..."
          gcloud run jobs create trabajoya-migrate \
            --region=us-central1 \
            --image=gcr.io/$PROJECT_ID/trabajoya-backend:$SHORT_SHA \
            --command="node" \
            --args="scripts/run-migrations.js" \
            --update-secrets=DATABASE_URL=DATABASE_URL:latest \
            --set-env-vars="NODE_ENV=production" \
            --set-cloudsql-instances=${_CLOUD_SQL_INSTANCE} \
            --memory=1Gi \
            --cpu=1 \
            --max-retries=1 \
            --task-timeout=300
        fi
        
        echo "🚀 Ejecutando migraciones..."
        gcloud run jobs execute trabajoya-migrate --region=us-central1 --wait

  # Paso 2: Ejecutar seed después de migraciones
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🌱 Configurando y ejecutando seed..."
        
        # Verificar que el secreto DATABASE_URL existe
        echo "🔍 Verificando que el secreto DATABASE_URL existe..."
        if ! gcloud secrets describe DATABASE_URL --project=trabajo-ya-483316 >/dev/null 2>&1; then
          echo "❌ Error: El secreto DATABASE_URL no existe en Secret Manager"
          exit 1
        fi
        echo "✅ Secreto DATABASE_URL verificado"
        
        # Verificar si el job existe y su estado
        JOB_EXISTS=$$(gcloud run jobs describe trabajoya-seed --region=us-central1 --format="value(name)" 2>/dev/null || echo "")
        NEEDS_CREATE=false
        
        if [ -n "$${JOB_EXISTS}" ]; then
          echo "ℹ️  El job trabajoya-seed ya existe, verificando estado..."
          
          # Verificar si está en estado de error
          JOB_READY=$$(gcloud run jobs describe trabajoya-seed --region=us-central1 --format="value(status.conditions[0].status)" 2>/dev/null || echo "False")
          
          if [ "$${JOB_READY}" != "True" ]; then
            echo "⚠️  El job está en estado de error o no listo, eliminándolo para recrear..."
            gcloud run jobs delete trabajoya-seed --region=us-central1 --quiet 2>/dev/null || true
            sleep 2
            NEEDS_CREATE=true
          else
            echo "✅ El job existe y está listo, actualizando..."
            if ! gcloud run jobs update trabajoya-seed \
              --region=us-central1 \
              --image=gcr.io/$PROJECT_ID/trabajoya-backend:$SHORT_SHA \
              --update-secrets=DATABASE_URL=DATABASE_URL:latest \
              --set-env-vars="NODE_ENV=production" \
              --set-cloudsql-instances=${_CLOUD_SQL_INSTANCE} \
              --memory=1Gi \
              --cpu=1 \
              --max-retries=1 \
              --task-timeout=300 2>/dev/null; then
              echo "⚠️  Error al actualizar, eliminando y recreando..."
              gcloud run jobs delete trabajoya-seed --region=us-central1 --quiet 2>/dev/null || true
              sleep 2
              NEEDS_CREATE=true
            else
              echo "✅ Job actualizado correctamente"
            fi
          fi
        else
          NEEDS_CREATE=true
        fi
        
        # Crear el job si es necesario
        if [ "$${NEEDS_CREATE}" = "true" ]; then
          echo "📝 Creando job trabajoya-seed..."
          gcloud run jobs create trabajoya-seed \
            --region=us-central1 \
            --image=gcr.io/$PROJECT_ID/trabajoya-backend:$SHORT_SHA \
            --command="node" \
            --args="scripts/run-seed.js" \
            --update-secrets=DATABASE_URL=DATABASE_URL:latest \
            --set-env-vars="NODE_ENV=production" \
            --set-cloudsql-instances=${_CLOUD_SQL_INSTANCE} \
            --memory=1Gi \
            --cpu=1 \
            --max-retries=1 \
            --task-timeout=300
        fi
        
        echo "🚀 Ejecutando seed..."
        gcloud run jobs execute trabajoya-seed --region=us-central1 --wait

  # Paso 3: Desplegar servicio principal
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🚀 Desplegando servicio..."
        
        # Verificar que el secreto DATABASE_URL existe
        echo "🔍 Verificando que el secreto DATABASE_URL existe..."
        if ! gcloud secrets describe DATABASE_URL --project=trabajo-ya-483316 >/dev/null 2>&1; then
          echo "❌ Error: El secreto DATABASE_URL no existe en Secret Manager"
          exit 1
        fi
        echo "✅ Secreto DATABASE_URL verificado"
        
        # Obtener el service account del servicio
        SERVICE_ACCOUNT=$$(gcloud run services describe trabajoya-backend --region=${_REGION} --format="value(spec.template.spec.serviceAccountName)" 2>/dev/null || echo "")
        
        # Si no tiene service account, usar el default compute service account
        if [ -z "$${SERVICE_ACCOUNT}" ]; then
          SERVICE_ACCOUNT="335199126550-compute@developer.gserviceaccount.com"
        fi
        
        echo "🔐 Verificando permisos del service account: $${SERVICE_ACCOUNT}"
        
        # Verificar y otorgar permisos para acceder a los secretos
        SECRETS=("DATABASE_URL" "JWT_ACCESS_SECRET" "GOOGLE_CLIENT_ID" "GOOGLE_CLIENT_SECRET" "AWS_ACCESS_KEY_ID" "AWS_SECRET_ACCESS_KEY" "RESEND_API_KEY" "OPENAI_API_KEY" "PAYPAL_CLIENT_ID" "PAYPAL_CLIENT_SECRET" "APPLE_PRIVATE_KEY")
        
        for SECRET in "$${SECRETS[@]}"; do
          # Verificar si el service account ya tiene acceso
          if ! gcloud secrets get-iam-policy "$${SECRET}" --project=trabajo-ya-483316 2>/dev/null | grep -q "$${SERVICE_ACCOUNT}"; then
            echo "  🔓 Otorgando acceso al secreto $${SECRET}..."
            gcloud secrets add-iam-policy-binding "$${SECRET}" \
              --project=trabajo-ya-483316 \
              --member="serviceAccount:$${SERVICE_ACCOUNT}" \
              --role="roles/secretmanager.secretAccessor" \
              --quiet 2>/dev/null || true
          fi
        done
        
        echo "✅ Permisos de secretos verificados"
        
        # Desplegar servicio (actualizar o crear)
        echo "🚀 Desplegando servicio trabajoya-backend..."
        gcloud run deploy trabajoya-backend \
          --image=gcr.io/$PROJECT_ID/trabajoya-backend:$SHORT_SHA \
          --region=${_REGION} \
          --platform=managed \
          --allow-unauthenticated \
          --memory=${_MEMORY} \
          --cpu=${_CPU} \
          --min-instances=${_MIN_INSTANCES} \
          --max-instances=${_MAX_INSTANCES} \
          --port=8080 \
          --timeout=300 \
          --concurrency=${_CONCURRENCY} \
          --service-account=$${SERVICE_ACCOUNT} \
          --set-env-vars="NODE_ENV=production,FRONTEND_URL=https://web.trabajo-ya.com,MAIL_PROVIDER=resend,MAIL_FROM=noreply@trabajo-ya.com,S3_BUCKET_NAME=trabajoya-prod-media,GCS_BUCKET_NAME=trabajoya-storage,GCP_PROJECT_ID=trabajo-ya-483316,AWS_REGION=us-east-1,CLOUDFRONT_DOMAIN=d193dyce2cbipr.cloudfront.net,OPENAI_MODEL=gpt-4o-mini,LAUNCH_TRIAL_START_AT=2026-02-01T00:00:00Z,LAUNCH_TRIAL_END_AT=2026-03-03T00:00:00Z,LAUNCH_TRIAL_DURATION_DAYS=4,JWT_ACCESS_EXPIRES_IN=15m,JWT_REFRESH_EXPIRES_IN=7d,GOOGLE_ANDROID_CLIENT_ID=335199126550-bbmp5fmhlbipkgc4vm1njl0grvdhicrb.apps.googleusercontent.com,GOOGLE_IOS_CLIENT_ID=335199126550-u4amua613a69oc4dpkau6rgt5uijiu98.apps.googleusercontent.com,APPLE_REDIRECT_URI=https://trabajo-ya.com/api/auth/apple/callback,APPLE_TEAM_ID=CC32GQQZ82,APPLE_KEY_ID=BH7JD8AKZ4,APPLE_CLIENT_ID=com.trabajoya.web,APPLE_BUNDLE_ID=com.trabajoya.app" \
          --set-secrets=DATABASE_URL=DATABASE_URL:latest,JWT_ACCESS_SECRET=JWT_ACCESS_SECRET:latest,GOOGLE_CLIENT_ID=GOOGLE_CLIENT_ID:latest,GOOGLE_CLIENT_SECRET=GOOGLE_CLIENT_SECRET:latest,AWS_ACCESS_KEY_ID=AWS_ACCESS_KEY_ID:latest,AWS_SECRET_ACCESS_KEY=AWS_SECRET_ACCESS_KEY:latest,RESEND_API_KEY=RESEND_API_KEY:latest,OPENAI_API_KEY=OPENAI_API_KEY:latest,PAYPAL_CLIENT_ID=PAYPAL_CLIENT_ID:latest,PAYPAL_CLIENT_SECRET=PAYPAL_CLIENT_SECRET:latest,APPLE_PRIVATE_KEY=APPLE_PRIVATE_KEY:latest \
          --set-cloudsql-instances=${_CLOUD_SQL_INSTANCE} \
          --quiet
        
        # Verificar que el despliegue fue exitoso
        if [ $$? -ne 0 ]; then
          echo "❌ Error al desplegar el servicio"
          exit 1
        fi
        
        echo "✅ Servicio desplegado. Verificando que los secretos están configurados..."
        
        # Esperar un momento para que el despliegue se complete
        sleep 5
        
        # Verificar que DATABASE_URL está configurada como secreto
        HAS_DATABASE_SECRET=$$(gcloud run services describe trabajoya-backend --region=${_REGION} --format="get(spec.template.spec.containers[0].env)" 2>/dev/null | grep -o "DATABASE_URL" | head -1 || echo "")
        
        if [ -z "$${HAS_DATABASE_SECRET}" ]; then
          echo "⚠️  DATABASE_URL no está configurada como variable de entorno. Reintentando despliegue..."
          
          # Intentar actualizar explícitamente solo los secretos
          gcloud run services update trabajoya-backend \
            --region=${_REGION} \
            --update-secrets=DATABASE_URL=DATABASE_URL:latest,JWT_ACCESS_SECRET=JWT_ACCESS_SECRET:latest,GOOGLE_CLIENT_ID=GOOGLE_CLIENT_ID:latest,GOOGLE_CLIENT_SECRET=GOOGLE_CLIENT_SECRET:latest,AWS_ACCESS_KEY_ID=AWS_ACCESS_KEY_ID:latest,AWS_SECRET_ACCESS_KEY=AWS_SECRET_ACCESS_KEY:latest,RESEND_API_KEY=RESEND_API_KEY:latest,OPENAI_API_KEY=OPENAI_API_KEY:latest,PAYPAL_CLIENT_ID=PAYPAL_CLIENT_ID:latest,PAYPAL_CLIENT_SECRET=PAYPAL_CLIENT_SECRET:latest,APPLE_PRIVATE_KEY=APPLE_PRIVATE_KEY:latest \
            --quiet
        fi
        
        echo "✅ Servicio desplegado correctamente"

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

substitutions:
  _REGION: 'us-central1'
  _MEMORY: '2Gi'
  _CPU: '2'
  _MIN_INSTANCES: '1'
  _MAX_INSTANCES: '10'
  _CONCURRENCY: '80'
  _CLOUD_SQL_INSTANCE: "trabajo-ya-483316:us-central1:trabajoya-db"

timeout: '900s'