steps:
  # Construir la imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.gcp'
      - '-t'
      - 'gcr.io/$PROJECT_ID/trabajoya-backend:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/trabajoya-backend:latest'
      - '.'

  # Enviar la imagen al Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/trabajoya-backend'

  # Paso 1: Configurar y ejecutar migraciones
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "📦 Configurando y ejecutando migraciones..."
        # Intentar actualizar primero, si falla crear
        gcloud run jobs update trabajoya-migrate \
          --region=us-central1 \
          --image=gcr.io/$PROJECT_ID/trabajoya-backend:$SHORT_SHA \
          --update-secrets=DATABASE_URL=trabajoya-secrets:latest \
          --set-env-vars="NODE_ENV=production" \
          --set-cloudsql-instances=${_CLOUD_SQL_INSTANCE} \
          --memory=1Gi \
          --cpu=1 \
          --max-retries=1 \
          --task-timeout=300 2>/dev/null || \
        gcloud run jobs create trabajoya-migrate \
          --region=us-central1 \
          --image=gcr.io/$PROJECT_ID/trabajoya-backend:$SHORT_SHA \
          --command="node" \
          --args="scripts/run-migrations.js" \
          --update-secrets=DATABASE_URL=trabajoya-secrets:latest \
          --set-env-vars="NODE_ENV=production" \
          --set-cloudsql-instances=${_CLOUD_SQL_INSTANCE} \
          --memory=1Gi \
          --cpu=1 \
          --max-retries=1 \
          --task-timeout=300
        
        echo "🚀 Ejecutando migraciones..."
        gcloud run jobs execute trabajoya-migrate --region=us-central1 --wait

  # Paso 2: Ejecutar seed después de migraciones
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🌱 Configurando y ejecutando seed..."
        # Intentar actualizar primero, si falla crear
        gcloud run jobs update trabajoya-seed \
          --region=us-central1 \
          --image=gcr.io/$PROJECT_ID/trabajoya-backend:$SHORT_SHA \
          --update-secrets=DATABASE_URL=trabajoya-secrets:latest \
          --set-env-vars="NODE_ENV=production" \
          --set-cloudsql-instances=${_CLOUD_SQL_INSTANCE} \
          --memory=1Gi \
          --cpu=1 \
          --max-retries=1 \
          --task-timeout=300 2>/dev/null || \
        gcloud run jobs create trabajoya-seed \
          --region=us-central1 \
          --image=gcr.io/$PROJECT_ID/trabajoya-backend:$SHORT_SHA \
          --command="node" \
          --args="scripts/run-seed.js" \
          --update-secrets=DATABASE_URL=trabajoya-secrets:latest \
          --set-env-vars="NODE_ENV=production" \
          --set-cloudsql-instances=${_CLOUD_SQL_INSTANCE} \
          --memory=1Gi \
          --cpu=1 \
          --max-retries=1 \
          --task-timeout=300
        
        echo "🚀 Ejecutando seed..."
        gcloud run jobs execute trabajoya-seed --region=us-central1 --wait

  # Paso 3: Desplegar servicio principal
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🚀 Desplegando servicio..."
        gcloud run deploy trabajoya-backend \
          --image=gcr.io/$PROJECT_ID/trabajoya-backend:$SHORT_SHA \
          --region=${_REGION} \
          --platform=managed \
          --allow-unauthenticated \
          --memory=${_MEMORY} \
          --cpu=${_CPU} \
          --min-instances=${_MIN_INSTANCES} \
          --max-instances=${_MAX_INSTANCES} \
          --port=8080 \
          --timeout=300 \
          --concurrency=${_CONCURRENCY} \
          --set-env-vars="NODE_ENV=production,FRONTEND_URL=https://web.trabajo-ya.com,MAIL_PROVIDER=resend,MAIL_FROM=noreply@trabajo-ya.com,S3_BUCKET_NAME=trabajoya-prod-media,GCS_BUCKET_NAME=trabajoya-storage,GCP_PROJECT_ID=trabajo-ya-483316,AWS_REGION=us-east-1,CLOUDFRONT_DOMAIN=d193dyce2cbipr.cloudfront.net,OPENAI_MODEL=gpt-4o-mini,LAUNCH_TRIAL_START_AT=2026-02-01T00:00:00Z,LAUNCH_TRIAL_END_AT=2026-03-03T00:00:00Z,LAUNCH_TRIAL_DURATION_DAYS=4,JWT_ACCESS_EXPIRES_IN=15m,JWT_REFRESH_EXPIRES_IN=7d,GOOGLE_ANDROID_CLIENT_ID=335199126550-bbmp5fmhlbipkgc4vm1njl0grvdhicrb.apps.googleusercontent.com,GOOGLE_IOS_CLIENT_ID=335199126550-u4amua613a69oc4dpkau6rgt5uijiu98.apps.googleusercontent.com,APPLE_REDIRECT_URI=https://trabajo-ya.com/api/auth/apple/callback,APPLE_TEAM_ID=CC32GQQZ82,APPLE_KEY_ID=BH7JD8AKZ4,APPLE_CLIENT_ID=com.trabajoya.web,APPLE_BUNDLE_ID=com.trabajoya.app" \
          --update-secrets=DATABASE_URL=trabajoya-secrets:latest,JWT_ACCESS_SECRET=trabajoya-secrets:latest,GOOGLE_CLIENT_ID=trabajoya-secrets:latest,GOOGLE_CLIENT_SECRET=trabajoya-secrets:latest,AWS_ACCESS_KEY_ID=trabajoya-secrets:latest,AWS_SECRET_ACCESS_KEY=trabajoya-secrets:latest,RESEND_API_KEY=trabajoya-secrets:latest,OPENAI_API_KEY=trabajoya-secrets:latest,PAYPAL_CLIENT_ID=trabajoya-secrets:latest,PAYPAL_CLIENT_SECRET=trabajoya-secrets:latest,APPLE_PRIVATE_KEY=trabajoya-secrets:latest \
          --set-cloudsql-instances=${_CLOUD_SQL_INSTANCE}

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

substitutions:
  _REGION: 'us-central1'
  _MEMORY: '2Gi'
  _CPU: '2'
  _MIN_INSTANCES: '1'
  _MAX_INSTANCES: '10'
  _CONCURRENCY: '80'
  _CLOUD_SQL_INSTANCE: "trabajo-ya-483316:us-central1:trabajoya-db"

timeout: '900s'