steps:
  # Construir la imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.gcp'
      - '-t'
      - 'gcr.io/$PROJECT_ID/trabajoya-backend:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/trabajoya-backend:latest'
      - '.'

  # Enviar la imagen al Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/trabajoya-backend'

  # Desplegar a Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🧹 Limpiando secrets antiguos (si existen)..."
        gcloud run services update trabajoya-backend \
          --region=${_REGION} \
          --clear-secrets \
          --no-traffic || echo "⚠️  No se pudieron limpiar secrets (puede ser normal si el servicio no existe)"
        
        echo "🚀 Desplegando servicio..."
        gcloud run deploy trabajoya-backend \
          --image=gcr.io/$PROJECT_ID/trabajoya-backend:$SHORT_SHA \
          --region=${_REGION} \
          --platform=managed \
          --allow-unauthenticated \
          --memory=${_MEMORY} \
          --cpu=${_CPU} \
          --min-instances=${_MIN_INSTANCES} \
          --max-instances=${_MAX_INSTANCES} \
          --port=8080 \
          --timeout=300 \
          --concurrency=${_CONCURRENCY} \
          --set-env-vars="NODE_ENV=production" \
          --set-secrets="TRABAJOYA_SECRETS=trabajoya-secrets:latest"

  # Crear/actualizar Cloud Run Job para migraciones
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "📦 Configurando Cloud Run Job para migraciones..."
        
        # Crear o actualizar el job de migraciones
        CLOUD_SQL_INSTANCE="$PROJECT_ID:${_REGION}:trabajoya-db"
        
        # Intentar crear el job primero
        if ! gcloud run jobs describe trabajoya-migrate --region=${_REGION} >/dev/null 2>&1; then
          echo "📦 Creando nuevo job trabajoya-migrate..."
          gcloud run jobs create trabajoya-migrate \
            --image=gcr.io/$PROJECT_ID/trabajoya-backend:$SHORT_SHA \
            --region=${_REGION} \
            --command="sh" \
            --args="scripts/load-secrets-and-run.sh,npx,prisma,migrate,deploy" \
            --set-secrets="TRABAJOYA_SECRETS=trabajoya-secrets:latest" \
            --set-env-vars="NODE_ENV=production" \
            --add-cloudsql-instances=$CLOUD_SQL_INSTANCE \
            --memory=1Gi \
            --cpu=1 \
            --max-retries=1 \
            --task-timeout=600
        else
          echo "🔄 Actualizando job trabajoya-migrate existente..."
          # Actualizar el job con todos los parámetros, incluyendo Cloud SQL
          gcloud run jobs update trabajoya-migrate \
            --image=gcr.io/$PROJECT_ID/trabajoya-backend:$SHORT_SHA \
            --region=${_REGION} \
            --command="sh" \
            --args="scripts/load-secrets-and-run.sh,npx,prisma,migrate,deploy" \
            --set-secrets="TRABAJOYA_SECRETS=trabajoya-secrets:latest" \
            --set-env-vars="NODE_ENV=production" \
            --set-cloudsql-instances=$CLOUD_SQL_INSTANCE \
            --memory=1Gi \
            --cpu=1 \
            --max-retries=1 \
            --task-timeout=600
        fi
        
        echo "🚀 Ejecutando migraciones..."
        gcloud run jobs execute trabajoya-migrate \
          --region=${_REGION} \
          --wait || echo "⚠️  Error en migraciones, pero continuando..."

  # Crear/actualizar Cloud Run Job para seed
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🌱 Configurando Cloud Run Job para seed..."
        
        # Crear o actualizar el job de seed
        CLOUD_SQL_INSTANCE="$PROJECT_ID:${_REGION}:trabajoya-db"
        
        # Intentar crear el job primero
        if ! gcloud run jobs describe trabajoya-seed --region=${_REGION} >/dev/null 2>&1; then
          echo "📦 Creando nuevo job trabajoya-seed..."
          gcloud run jobs create trabajoya-seed \
            --image=gcr.io/$PROJECT_ID/trabajoya-backend:$SHORT_SHA \
            --region=${_REGION} \
            --command="sh" \
            --args="scripts/load-secrets-and-run.sh,node,scripts/seed-if-empty.js" \
            --set-secrets="TRABAJOYA_SECRETS=trabajoya-secrets:latest" \
            --set-env-vars="NODE_ENV=production" \
            --add-cloudsql-instances=$CLOUD_SQL_INSTANCE \
            --memory=1Gi \
            --cpu=1 \
            --max-retries=1 \
            --task-timeout=600
        else
          echo "🔄 Actualizando job trabajoya-seed existente..."
          # Actualizar el job con todos los parámetros, incluyendo Cloud SQL
          gcloud run jobs update trabajoya-seed \
            --image=gcr.io/$PROJECT_ID/trabajoya-backend:$SHORT_SHA \
            --region=${_REGION} \
            --command="sh" \
            --args="scripts/load-secrets-and-run.sh,node,scripts/seed-if-empty.js" \
            --set-secrets="TRABAJOYA_SECRETS=trabajoya-secrets:latest" \
            --set-env-vars="NODE_ENV=production" \
            --set-cloudsql-instances=$CLOUD_SQL_INSTANCE \
            --memory=1Gi \
            --cpu=1 \
            --max-retries=1 \
            --task-timeout=600
        fi
        
        echo "🚀 Ejecutando seed (solo si la DB está vacía)..."
        gcloud run jobs execute trabajoya-seed \
          --region=${_REGION} \
          --wait || echo "⚠️  Error en seed, pero continuando..."

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

substitutions:
  _REGION: 'us-central1'
  _MEMORY: '2Gi'
  _CPU: '2'
  _MIN_INSTANCES: '1'
  _MAX_INSTANCES: '10'
  _CONCURRENCY: '80'

timeout: '1200s'

