-- AlterEnum
ALTER TYPE "CatalogType" ADD VALUE 'JOB_TYPES';
ALTER TYPE "CatalogType" ADD VALUE 'EXPERIENCE_LEVELS';
ALTER TYPE "CatalogType" ADD VALUE 'APPLICATION_STATUSES';
ALTER TYPE "CatalogType" ADD VALUE 'MODALITIES';
ALTER TYPE "CatalogType" ADD VALUE 'LANGUAGE_LEVELS';
ALTER TYPE "CatalogType" ADD VALUE 'COMPANY_SIZES';
ALTER TYPE "CatalogType" ADD VALUE 'SECTORS';
ALTER TYPE "CatalogType" ADD VALUE 'STUDY_TYPES';
ALTER TYPE "CatalogType" ADD VALUE 'STUDY_STATUSES';
ALTER TYPE "CatalogType" ADD VALUE 'MARITAL_STATUSES';

